import java.awt.event.KeyListener;
import java.awt.event.KeyEvent;
import java.awt.event.ActionEvent;

/**
 * KeyListener for Dragon Dungeon game
 * 
 * @author Michael Damian Mulligan
 * @version March 31, 2011
 */
public class DragonDungeonKeyListener implements KeyListener
{
    private GraphicalDragonDungeon game;

    /**
     * Constructor for objects of class DragonDungeonKeyListener
     * @param gameScreen The window used to display the game
     */
    public DragonDungeonKeyListener(GraphicalDragonDungeon gameScreen)
    {
        game = gameScreen;
    }

    /**
     * When a key is released, send the command to the game
     * Sends command by triggering actionPerformed in the game with a dummy button which has been assigned the relevent command
     * @param e The KeyEvent generated by the game
     */
    @Override
    public void keyReleased(KeyEvent e){
        int lastKey = e.getKeyCode();
        switch(lastKey){
            case KeyEvent.VK_W:
            case KeyEvent.VK_UP:
                game.actionPerformed(new ActionEvent(new GameButton("A", "MU"), 1, ""));
                break;
            case KeyEvent.VK_S:
            case KeyEvent.VK_DOWN:
                game.actionPerformed(new ActionEvent(new GameButton("A", "MD"), 1, ""));
                break;
            case KeyEvent.VK_A:
            case KeyEvent.VK_LEFT:
                game.actionPerformed(new ActionEvent(new GameButton("A", "ML"), 1, ""));
                break;
            case KeyEvent.VK_D:
            case KeyEvent.VK_RIGHT:
                game.actionPerformed(new ActionEvent(new GameButton("A", "MR"), 1, ""));
                break;
            case KeyEvent.VK_I:
                game.actionPerformed(new ActionEvent(new GameButton("A", "FU"), 1, ""));
                break;
            case KeyEvent.VK_K:
                game.actionPerformed(new ActionEvent(new GameButton("A", "FD"), 1, ""));
                break;
            case KeyEvent.VK_J:
                game.actionPerformed(new ActionEvent(new GameButton("A", "FL"), 1, ""));
                break;
            case KeyEvent.VK_L:
                game.actionPerformed(new ActionEvent(new GameButton("A", "FR"), 1, ""));
                break;
            default:
                return;
        }
        return;
    }
    
    /**
     * Not used, mandatory for KeyListener
     */
    @Override
    public void keyPressed(KeyEvent e){
        return;
    }
    /**
     * Not used, mandatory for KeyListener
     */
    @Override
    public void keyTyped(KeyEvent e){
        return;
    }
}
